### ISSUE TITLE
Remote CMD and callback feature Request

### ISSUE THREAD

**Issue by SgtPooki** [serkanyersen/sync#7]
Do you have any plans to support running build commands on the remote server after a certain file has been uploaded?

For example, I develop locally, sync files to a remote, and then usually run some sort of build command on the remote machine (local builds not possible unfortunately). Allowing me to run a specified command in the folder where the file changed would be excellent. A callback that allows me to refresh the browser locally once that remote command succeeds would be even more dreamy.

**Comment by serkanyersen** [comment]
This would be out of scope for this project because it's only supposed to upload files to a server.

I would suggest setting up a file watcher on the server and run any command you want on the server.
Use something like [fsmonitor](https://www.npmjs.com/package/fsmonitor). You can setup a watcher and run commands when those files changed such as
```
fsmonitor -s -p '+*.js' npm test
```

if you don't want or can't do this on the remote server, install fsmonitor locally and run this

```
fsmonitor -s -p '+*.js' ssh server.com 'cd project/path; npm test'
```

You should configure your ssh to not to ask password though.

Hope this helps
